debugQrCode: false
qrcodeSharpenBlur: 5
qrcodeSharpenWeight: 0.8
cameras: 
  - name: 'kinect'
    hfov: 58
    vfov: 45
    image_width: 640
    image_height: 480
  - name: 'left_camera'
    hfov: 60
    vfov: 33.75
    image_width: 1280
    image_height: 720 
  - name: 'right_camera'
    hfov: 60
    vfov: 33.75
    image_width: 1280
    image_height: 720 

